# Generated by Django 5.0.2 on 2026-04-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_user_discord_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="time_format",
            field=models.CharField(
                choices=[("24h", "24 hour"), ("12h", "12 hour")],
                default="12h",
                help_text="Whether to display times as 24-hour or 12-hour",
                max_length=4,
                verbose_name="time format",
            ),
        ),
    ]
