# Generated by Django 5.0.2 on 2026-09-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_user_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="highlight_hashtags",
            field=models.BooleanField(
                default=True,
                help_text="Whether #hashtags render as a highlighted, clickable chip. When off they still link to the tag's page, just without the pill styling — this only affects rendering.",
                verbose_name="highlight hashtags",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="highlight_properties",
            field=models.BooleanField(
                default=True,
                help_text="Whether key::value block properties render as a highlighted, clickable chip. When off they still link to the matching saved view, just without the pill styling — this only affects rendering.",
                verbose_name="highlight properties",
            ),
        ),
    ]
