# Generated by hand (not `makemigrations`) so the existing
# `highlight_properties` column is renamed rather than dropped and
# recreated — non-interactive makemigrations can't detect a rename on
# its own and would otherwise produce a RemoveField + AddField pair
# that silently resets everyone's saved preference back to the default.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_user_highlight_hashtags_user_highlight_properties"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="highlight_properties",
            new_name="highlight_property_keys",
        ),
        migrations.AlterField(
            model_name="user",
            name="highlight_property_keys",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Whether the `key::` part of a block property renders as a "
                    "highlighted, clickable chip. When off it still links to "
                    "the matching saved view, just without the pill styling "
                    "— this only affects rendering."
                ),
                verbose_name="highlight property keys",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="highlight_property_values",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Whether the value part of a `key::value` block property "
                    "renders in a softer, lower-contrast highlight. When off "
                    "it displays as plain text — this only affects rendering."
                ),
                verbose_name="highlight property values",
            ),
        ),
    ]
