# Generated by Django 5.0.2 on 2026-04-29 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_replace_kind_with_types"),
        ("knowledge", "0023_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocks",
                to="assets.asset",
            ),
        ),
    ]
