# Generated by Django 5.0.2 on 2026-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0026_page_favorited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
