# Generated by Django 5.0.2 on 2026-05-07 02:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0029_page_favorite_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("bullet", "Bullet Point"),
                    ("todo", "Todo"),
                    ("doing", "Doing"),
                    ("done", "Done"),
                    ("later", "Later"),
                    ("wontdo", "Won't Do"),
                    ("heading", "Heading"),
                    ("quote", "Quote"),
                    ("code", "Code Block"),
                    ("divider", "Divider"),
                    ("query", "Saved View Embed"),
                ],
                default="bullet",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable view name", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier, unique per user",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional one-liner shown alongside the view",
                        max_length=500,
                    ),
                ),
                (
                    "filter",
                    models.JSONField(
                        default=dict,
                        help_text="Structured filter spec — see knowledge.services.query_engine",
                    ),
                ),
                (
                    "sort",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ordering, e.g. [{"field": "scheduled_for", "dir": "asc"}]',
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Bundled view — read-only for users; cloned via 'duplicate'",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_views",
                "ordering": ("-is_system", "name"),
            },
        ),
        migrations.AddField(
            model_name="block",
            name="query_view",
            field=models.ForeignKey(
                blank=True,
                help_text="When block_type='query', the SavedView this block embeds",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="embed_blocks",
                to="knowledge.savedview",
            ),
        ),
        migrations.AddIndex(
            model_name="savedview",
            index=models.Index(
                fields=["user", "is_system"], name="saved_views_user_id_5e7772_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedview",
            unique_together={("user", "slug")},
        ),
    ]
