# Generated by Django 5.0.2 on 2026-06-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0038_block_due_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageembeddedview",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order within the embedded-views section"
            ),
        ),
    ]
