# Generated by Django 5.0.2 on 2026-06-30 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_replace_kind_with_types"),
        ("knowledge", "0039_alter_pageembeddedview_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="block",
            name="blocks_user_id_e91738_idx",
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["user", "due_at"], name="blocks_user_id_f99b9a_idx"
            ),
        ),
    ]
