# Generated by Django 5.0.2 on 2026-07-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0040_block_due_at_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminderaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("complete", "Mark complete"),
                    ("mark_doing", "Mark doing"),
                    ("move_to_today", "Move to today's daily note"),
                    ("snooze_15m", "Snooze 15 minutes"),
                    ("snooze_30m", "Snooze 30 minutes"),
                    ("snooze_1h", "Snooze 1 hour"),
                    ("snooze_1d", "Snooze 1 day"),
                ],
                max_length=32,
            ),
        ),
    ]
