# Generated by Django 5.0.2 on 2026-07-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0041_reminderaction_move_to_today"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedview",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Archived views are tucked away from the main saved-views list and the left-nav until unarchived — for short-lived views that shouldn't clutter the list",
            ),
        ),
    ]
