# Generated by Django 5.0.2 on 2026-07-19 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_replace_kind_with_types"),
        ("knowledge", "0043_alter_reminderaction_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="created_via",
            field=models.CharField(
                choices=[("web", "Web"), ("ai_chat", "AI Chat"), ("mcp", "MCP")],
                default="web",
                help_text="Which surface created this block (web UI, AI chat, MCP)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["created_via"], name="blocks_created_321eec_idx"
            ),
        ),
    ]
