# Generated by Django 5.0.2 on 2026-07-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0044_block_created_via_block_blocks_created_321eec_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageembeddedview",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                ],
                default="",
                help_text="Accent color for the embed's border/title on the page — lets an embed (e.g. an overdue view) stand out. Empty = no accent.",
                max_length=16,
            ),
        ),
    ]
