# Generated by Django 5.0.2 on 2026-07-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0045_pageembeddedview_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="push_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When browser push delivery was attempted for this reminder. Set once, on the first tick, regardless of per-subscription success — push fans out to N devices, so unlike `sent_at` (which gates the Discord retry loop) this never triggers a resend; a stale or unreachable device just doesn't get this one notification.",
                null=True,
            ),
        ),
    ]
