# Generated by Django 5.0.2 on 2026-09-23 00:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0046_automationrun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Identifier used inside {{...}}: lowercase letters, digits, _",
                        max_length=64,
                    ),
                ),
                (
                    "expansion",
                    models.TextField(
                        help_text="Text the variable expands to; may contain other {{tokens}}"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_variables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_variables",
                "ordering": ("name",),
            },
        ),
        migrations.AddConstraint(
            model_name="customvariable",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uniq_custom_variable_user_name"
            ),
        ),
    ]
