# Generated by Django 5.0.2 on 2026-09-23 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0047_custom_variable"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("content", models.TextField(blank=True)),
                ("block_type", models.CharField(max_length=20)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("due_at_has_time", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("automation", "Automation"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="knowledge.block",
                    ),
                ),
            ],
            options={
                "db_table": "block_revisions",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["block", "-created_at"],
                        name="block_revis_block_i_175336_idx",
                    )
                ],
            },
        ),
    ]
