# Generated by Django 5.0.2 on 2026-09-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0047_custom_variable"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="block",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Designates whether this object should be treated as active. Unselect this instead of deleting objects.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Designates whether this object should be treated as active. Unselect this instead of deleting objects.",
                verbose_name="active",
            ),
        ),
    ]
