# Generated by Django 5.0.2 on 2026-09-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0048_block_deleted_at_block_is_active_page_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
