# Generated by Django 5.0.2 on 2026-09-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0048_blockrevision"),
        ("knowledge", "0049_alter_block_deleted_at_alter_page_deleted_at"),
    ]

    operations = []
