# Generated by Django 5.0.2 on 2026-09-30 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0050_merge_block_revision_and_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationBlockMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("automation_block_uuid", models.UUIDField(db_index=True)),
                ("matched_block_uuid", models.UUIDField(db_index=True)),
                (
                    "first_matched_at",
                    models.DateTimeField(
                        help_text="When this block first started matching the automation's query (or last had a watched field change)"
                    ),
                ),
                (
                    "fingerprint",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of the automation's watch:: fields/tags at first_matched_at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_block_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "automation_block_matches",
                "indexes": [
                    models.Index(
                        fields=["automation_block_uuid"],
                        name="automation__automat_b302aa_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="automationblockmatch",
            constraint=models.UniqueConstraint(
                fields=("automation_block_uuid", "matched_block_uuid"),
                name="uniq_automation_block_match",
            ),
        ),
    ]
