# Generated by Django 5.0.2 on 2026-04-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0015_pendingtoolapproval_auto_approve_notes_writes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="name",
            field=models.CharField(
                help_text="Model name (e.g., gpt-4, claude-opus-4-7)",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="pendingtoolapproval",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
