# Generated by Django 5.0.2 on 2026-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0016_alter_aimodel_name_alter_pendingtoolapproval_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="attachments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
