# Generated by Django 5.0.2 on 2026-05-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0017_chatmessage_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingtoolapproval",
            name="current_page_uuid",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
