# Generated by Django 5.0.2 on 2026-06-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0022_aimodel_capability_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("complete", "Complete"),
                    ("streaming", "Streaming"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="complete",
                max_length=20,
            ),
        ),
    ]
