from core.commands.login_command import LoginCommand
from core.commands.logout_command import LogoutCommand
from core.commands.register_command import RegisterCommand
from core.commands.update_discord_webhook_command import UpdateDiscordWebhookCommand
from core.commands.update_theme_command import UpdateThemeCommand
from core.commands.update_time_format_command import UpdateTimeFormatCommand
from core.commands.update_timezone_command import UpdateTimezoneCommand
