import Head from 'next/head'
import {Inter} from 'next/font/google'
import {invoke} from '@tauri-apps/api/tauri'
import styles from '@/styles/Home.module.css'
import {useEffect, useState} from 'react'

const inter = Inter({subsets: ['latin']})

// Note: When working with Next.js in development you have 2 execution contexts:
// - The server (nodejs), where Tauri cannot be reached, because the current context is inside of nodejs.
// - The client (webview), where it is possible to interact with the Tauri rust backend.
// To check if we are currently executing in the client context, we can check the type of the window object;
const isClient = typeof window !== 'undefined'

// Now we can call our Command!
// Right-click on the application background and open the developer tools.
// You will see "Hello, World!" printed in the console.
// isClient &&
//   invoke('greet', { name: 'World' }).then(console.log).catch(console.error)

export default function Home() {
  useEffect(() => {
    invoke('greet', {name: 'World'})
      .then(console.log)
      .catch(console.error)
  }, [])

  const [links, setLinks] = useState('')
  const [tags, setTags] = useState('')

  const [loadingClass, setLoadingClass] = useState('')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css"></link>
      </Head>
      <main className={styles.main}>

        <div className="container">
          <div className="columns">

            <div className="column">
              <textarea name=""
                        id=""
                        className="textarea is-primary mt-4"
                        rows={10}
                        value={links}
                        placeholder={'comma separate list of links...'}
                        onChange={e => setLinks(e.target.value)}>
              </textarea>
              <textarea name=""
                        id=""
                        className="textarea is-primary mt-4"
                        rows={10}
                        value={tags}
                        onChange={e => setTags(e.target.value)}>

              </textarea>
            </div>

          </div>
          <button className={"button is-primary " + loadingClass}
                  onClick={() => {
                    setLoadingClass('is-loading')}
                  }>
            Submit
          </button>
        </div>
      </main>
    </>
  )
}
