# Generated by Django 5.0.2 on 2026-09-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_archives", "0002_soft_delete_and_set_null_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webarchive",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
